import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout";
import { Head, router } from "@inertiajs/react";
import { useState } from "react";

export default function TechnicianHoursReport({ employees = [], entries = [], dailyRows = [], summaries = [], totalDayHours = 0, totalWorkHours = 0, totalUnallocatedHours = 0, filters }) {
    const [data, setData] = useState(filters);
    const update = (key, value) => setData((current) => ({ ...current, [key]: value }));
    const submit = (event) => { event.preventDefault(); router.get(route("reports.technician-hours.index"), data, { preserveState: true, replace: true }); };
    const hours = (value) => Number(value || 0).toLocaleString("ro-RO", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    const workLabel = (entry) => entry.work_order ? [entry.work_order.number, entry.work_order.client_name].filter(Boolean).join(" — ") : "—";

    return <AuthenticatedLayout><Head title="Raport ore tehnicieni" /><div className="mx-auto max-w-7xl px-4 py-8">
        <div className="mb-6"><h1 className="text-3xl font-bold text-slate-900">Raport tehnicieni pe ore</h1><p className="mt-1 text-slate-500">Compară Start / Stop zi cu Start / Stop lucrare.</p></div>
        <form onSubmit={submit} className="mb-6 rounded-2xl border bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-4">
            <label className="text-sm font-semibold">Perioadă<select value={data.period} onChange={(event) => update("period", event.target.value)} className="mt-1 block w-full rounded-lg border-slate-300"><option value="day">Zi</option><option value="week">Săptămână</option><option value="month">Lună</option><option value="year">An</option><option value="custom">Interval ales</option></select></label>
            {data.period !== "custom" ? <label className="text-sm font-semibold">Data de referință<input type="date" value={data.date} onChange={(event) => update("date", event.target.value)} className="mt-1 block w-full rounded-lg border-slate-300" /></label> : <><label className="text-sm font-semibold">De la<input type="date" value={data.start_date} onChange={(event) => update("start_date", event.target.value)} className="mt-1 block w-full rounded-lg border-slate-300" /></label><label className="text-sm font-semibold">Până la<input type="date" value={data.end_date} onChange={(event) => update("end_date", event.target.value)} className="mt-1 block w-full rounded-lg border-slate-300" /></label></>}
            <label className="text-sm font-semibold">Tehnician<select value={data.employee_id} onChange={(event) => update("employee_id", event.target.value)} className="mt-1 block w-full rounded-lg border-slate-300"><option value="">Toți tehnicienii</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.name}</option>)}</select></label>
            <div className="flex items-end"><button className="w-full rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white hover:bg-blue-700">Aplică filtrele</button></div>
        </div></form>
        <div className="mb-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-slate-800 p-5 text-white"><div className="text-sm text-slate-300">Ore nete în zi</div><div className="mt-1 text-3xl font-bold">{hours(totalDayHours)} h</div><div className="mt-1 text-sm text-slate-300">Start zi / Stop zi, minus pauze</div></div><div className="rounded-2xl bg-blue-600 p-5 text-white"><div className="text-sm text-blue-100">Ore efective pe lucrări</div><div className="mt-1 text-3xl font-bold">{hours(totalWorkHours)} h</div><div className="mt-1 text-sm text-blue-100">Start lucrare / Stop lucrare</div></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="text-sm text-amber-800">Timp nealocat lucrărilor</div><div className="mt-1 text-3xl font-bold text-amber-950">{hours(totalUnallocatedHours)} h</div><div className="mt-1 text-sm text-amber-800">{filters.start_date} — {filters.end_date}</div></div></div>
        <section className="mb-6 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b px-5 py-4"><h2 className="font-bold">Comparație pe tehnician</h2><p className="mt-1 text-sm text-slate-500">„Nealocat” = timp net din zi care nu are interval Start / Stop lucrare.</p></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-slate-600"><tr><th className="px-5 py-3">Tehnician</th><th className="px-5 py-3 text-right">Zile</th><th className="px-5 py-3 text-right">Ore în zi</th><th className="px-5 py-3 text-right">Ore lucrări</th><th className="px-5 py-3 text-right">Nealocat</th><th className="px-5 py-3 text-right">Peste program</th></tr></thead><tbody>{summaries.map((summary) => <tr key={summary.employee_id} className="border-t"><td className="px-5 py-3 font-medium">{summary.employee_name}</td><td className="px-5 py-3 text-right">{summary.attendance_days}</td><td className="px-5 py-3 text-right">{hours(summary.day_minutes / 60)} h</td><td className="px-5 py-3 text-right font-semibold">{hours(summary.work_minutes / 60)} h</td><td className="px-5 py-3 text-right text-amber-700">{hours(summary.unallocated_minutes / 60)} h</td><td className="px-5 py-3 text-right text-rose-700">{hours(summary.overallocated_minutes / 60)} h</td></tr>)}{summaries.length === 0 && <tr><td colSpan="6" className="px-5 py-8 text-center text-slate-500">Nu există ore înregistrate pentru filtrele alese.</td></tr>}</tbody></table></div></section>
        <section className="mb-6 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b px-5 py-4"><h2 className="font-bold">Diferențe pe zi</h2></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-slate-600"><tr><th className="px-4 py-3">Data</th><th className="px-4 py-3">Tehnician</th><th className="px-4 py-3">Start / Stop zi</th><th className="px-4 py-3 text-right">Pauză</th><th className="px-4 py-3 text-right">Ore nete zi</th><th className="px-4 py-3 text-right">Ore lucrări</th><th className="px-4 py-3 text-right">Nealocat</th></tr></thead><tbody>{dailyRows.map((row) => <tr key={[row.employee_id, row.date].join("-")} className="border-t"><td className="px-4 py-3">{row.date}</td><td className="px-4 py-3 font-medium">{row.employee_name}</td><td className="px-4 py-3">{row.check_in} — {row.check_out}</td><td className="px-4 py-3 text-right">{row.break_minutes} min</td><td className="px-4 py-3 text-right">{hours(row.net_minutes / 60)} h</td><td className="px-4 py-3 text-right">{hours(row.work_minutes / 60)} h</td><td className="px-4 py-3 text-right text-amber-700">{hours(row.unallocated_minutes / 60)} h</td></tr>)}{dailyRows.length === 0 && <tr><td colSpan="7" className="px-4 py-8 text-center text-slate-500">Nu există zile închise cu Start / Stop zi pentru perioada aleasă.</td></tr>}</tbody></table></div></section>
        <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b px-5 py-4"><h2 className="font-bold">Detalii intervale pe lucrări</h2></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-slate-600"><tr><th className="px-4 py-3">Data</th><th className="px-4 py-3">Tehnician</th><th className="px-4 py-3">Lucrare</th><th className="px-4 py-3">Start</th><th className="px-4 py-3">Stop</th><th className="px-4 py-3 text-right">Ore</th></tr></thead><tbody>{entries.map((entry) => <tr key={entry.id} className="border-t"><td className="px-4 py-3">{entry.date}</td><td className="px-4 py-3 font-medium">{entry.employee_name}</td><td className="px-4 py-3">{workLabel(entry)}</td><td className="px-4 py-3">{entry.started_at}</td><td className="px-4 py-3">{entry.ended_at}</td><td className="px-4 py-3 text-right font-semibold">{hours(entry.hours)} h</td></tr>)}{entries.length === 0 && <tr><td colSpan="6" className="px-4 py-8 text-center text-slate-500">Nu există intervale de lucru pentru perioada aleasă.</td></tr>}</tbody></table></div></section>
    </div></AuthenticatedLayout>;
}
