import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout";
import { Head, router, useForm } from "@inertiajs/react";
import { useState } from "react";

const blank = { name: "", code: "", inventory_account: "371", expense_account: "607", revenue_account: "707", notes: "", active: true };

export default function Index({ categories = [], accounts = [] }) {
    const form = useForm(blank); const [editing, setEditing] = useState(null);
    const submit = (event) => { event.preventDefault(); if (editing) form.put(route("product-categories.update", editing.id), { onSuccess: () => { setEditing(null); form.reset(); } }); else form.post(route("product-categories.store"), { onSuccess: () => form.reset() }); };
    const openEdit = (category) => { setEditing(category); form.setData({ ...category }); };
    return <AuthenticatedLayout><Head title="Categorii produse" /><div className="mx-auto max-w-7xl px-4 py-8"><div className="mb-6"><h1 className="text-3xl font-bold">Categorii produse și conturi contabile</h1><p className="mt-1 text-slate-500">Alege conturile din planul contabil disponibil. Ele se preiau automat în recepțiile viitoare.</p></div><datalist id="chart-accounts">{accounts.map((account) => <option key={account.code} value={account.code}>{account.name}</option>)}</datalist><form onSubmit={submit} className="mb-6 grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-3"><input required placeholder="Denumire categorie" value={form.data.name} onChange={(e) => form.setData("name", e.target.value)} className="rounded-lg border-slate-300" /><input placeholder="Cod intern" value={form.data.code || ""} onChange={(e) => form.setData("code", e.target.value)} className="rounded-lg border-slate-300" /><input list="chart-accounts" placeholder="Cont stoc (ex. 371)" value={form.data.inventory_account} onChange={(e) => form.setData("inventory_account", e.target.value)} className="rounded-lg border-slate-300" /><input list="chart-accounts" placeholder="Cont cheltuială (ex. 607)" value={form.data.expense_account} onChange={(e) => form.setData("expense_account", e.target.value)} className="rounded-lg border-slate-300" /><input list="chart-accounts" placeholder="Cont venit (ex. 707)" value={form.data.revenue_account} onChange={(e) => form.setData("revenue_account", e.target.value)} className="rounded-lg border-slate-300" /><button className="rounded-lg bg-blue-600 px-4 py-2 font-bold text-white">{editing ? "Salvează categoria" : "Adaugă categoria"}</button>{editing && <button type="button" onClick={() => { setEditing(null); form.reset(); }} className="rounded-lg border px-4 py-2">Anulează</button>}</form><div className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="p-4">Categorie</th><th className="p-4">Produse</th><th className="p-4">Stoc</th><th className="p-4">Cheltuială</th><th className="p-4">Venit</th><th className="p-4"></th></tr></thead><tbody>{categories.map((category) => <tr key={category.id} className="border-t"><td className="p-4 font-semibold">{category.name}<span className="ml-2 text-slate-500">{category.code}</span></td><td className="p-4">{category.products_count}</td><td className="p-4">{category.inventory_account}</td><td className="p-4">{category.expense_account}</td><td className="p-4">{category.revenue_account}</td><td className="p-4 text-right"><button onClick={() => openEdit(category)} className="rounded border px-3 py-1">Editează</button></td></tr>)}</tbody></table></div><p className="mt-4 text-sm text-slate-500">Plan disponibil: {accounts.length} conturi operaționale relevante (stocuri, terți, TVA, trezorerie, cheltuieli și venituri).</p></div></AuthenticatedLayout>;
}
