import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout";
import { Head, Link, router } from "@inertiajs/react";
import { useState } from "react";

const money = (value) => new Intl.NumberFormat("ro-RO", { style: "currency", currency: "RON" }).format(Number(value || 0));
const sourceLabels = { invoice: "Factură", bon: "Bon fiscal", proforma: "Proformă / avans", chitanta: "Chitanță", other: "Altele" };
const methodLabels = { cash: "Numerar", pos: "POS / card", bank_transfer: "Transfer bancar", check: "CEC", cod: "Ramburs", other: "Altele" };

export default function Index({ receipts = [], filters = {}, totals = {} }) {
    const [data, setData] = useState({ from: filters.from || "", to: filters.to || "", register_type: filters.register_type || "", source_type: filters.source_type || "", payment_method: filters.payment_method || "" });
    const apply = (event) => { event.preventDefault(); router.get(route("financial-reports.receipts.index"), data, { preserveState: true, replace: true }); };
    const reset = () => { const empty = { from: "", to: "", register_type: "", source_type: "", payment_method: "" }; setData(empty); router.get(route("financial-reports.receipts.index"), empty, { replace: true }); };

    return <AuthenticatedLayout><Head title="Raport încasări" /><div className="mx-auto max-w-7xl px-4 py-8">
        <div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">Raport încasări</h1><p className="mt-1 text-slate-500">Centralizator pentru facturi, bonuri fiscale, chitanțe și alte încasări.</p></div><Link href={route("receipts.index")} className="rounded-lg border px-4 py-2 font-semibold text-slate-700">Registru încasări →</Link></div>
        <div className="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card label="Încasări brute" value={money(totals.gross)} className="bg-slate-800 text-white" /><Card label="Retururi" value={money(totals.returns)} className="bg-rose-50 text-rose-800 ring-1 ring-rose-200" /><Card label="Încasări nete" value={money(totals.net)} className="bg-emerald-600 text-white" /><Card label="Numerar / bancă" value={`${money(totals.cash)} / ${money(totals.bank)}`} className="bg-blue-50 text-blue-950 ring-1 ring-blue-200" /></div>
        <form onSubmit={apply} className="mb-6 grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-3 lg:grid-cols-6"><input type="date" value={data.from} onChange={(e) => setData({ ...data, from: e.target.value })} className="rounded-lg border-slate-300" /><input type="date" value={data.to} onChange={(e) => setData({ ...data, to: e.target.value })} className="rounded-lg border-slate-300" /><select value={data.register_type} onChange={(e) => setData({ ...data, register_type: e.target.value })} className="rounded-lg border-slate-300"><option value="">Toate registrele</option><option value="cash">Casierie</option><option value="bank">Bancă</option></select><select value={data.source_type} onChange={(e) => setData({ ...data, source_type: e.target.value })} className="rounded-lg border-slate-300"><option value="">Toate sursele</option>{Object.entries(sourceLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={data.payment_method} onChange={(e) => setData({ ...data, payment_method: e.target.value })} className="rounded-lg border-slate-300"><option value="">Toate metodele</option>{Object.entries(methodLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><div className="flex gap-2"><button className="rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white">Filtrează</button><button type="button" onClick={reset} className="rounded-lg border px-3 py-2">Reset</button></div></form>
        <div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-slate-600"><tr><th className="px-5 py-3">Data</th><th className="px-5 py-3">Sursă / document</th><th className="px-5 py-3">Client</th><th className="px-5 py-3">Încasare</th><th className="px-5 py-3">Metodă</th><th className="px-5 py-3 text-right">Sumă</th></tr></thead><tbody>{receipts.map((receipt) => <tr key={receipt.id} className="border-t"><td className="px-5 py-3">{receipt.received_at}</td><td className="px-5 py-3"><div className="font-medium">{sourceLabels[receipt.source_type] || receipt.source_type}{receipt.is_return && <span className="ml-2 text-rose-600">RETUR</span>}</div><div className="text-slate-500">{receipt.document || "—"}</div></td><td className="px-5 py-3">{receipt.client || "—"}</td><td className="px-5 py-3">{receipt.register_type === "cash" ? "Casierie" : "Bancă"}</td><td className="px-5 py-3">{methodLabels[receipt.payment_method] || receipt.payment_method}</td><td className={receipt.signed_amount < 0 ? "px-5 py-3 text-right font-bold text-rose-700" : "px-5 py-3 text-right font-bold text-emerald-700"}>{money(receipt.signed_amount)}</td></tr>)}{receipts.length === 0 && <tr><td colSpan="6" className="px-5 py-8 text-center text-slate-500">Nu există încasări pentru filtrele alese.</td></tr>}</tbody></table></div></div>
    </div></AuthenticatedLayout>;
}

function Card({ label, value, className }) { return <div className={`rounded-2xl p-5 ${className}`}><div className="text-sm opacity-80">{label}</div><div className="mt-1 text-2xl font-bold">{value}</div></div>; }
