import { Link, router } from "@inertiajs/react";
import { useMemo, useState } from "react";

const money = (value) => `${Number(value || 0).toLocaleString("ro-RO", { maximumFractionDigits: 0 })} RON`;
const workStatus = { noua: "Nouă", programata: "Programată", lucru: "În lucru", finalizata: "Finalizată", anulata: "Anulată" };

function Sparkline({ values = [] }) {
    const max = Math.max(...values, 1);
    const points = values.length > 1 ? values.map((value, index) => `${(index / (values.length - 1)) * 100},${38 - (Number(value || 0) / max) * 30}`).join(" ") : "0,38 100,38";
    return <svg viewBox="0 0 100 40" preserveAspectRatio="none" className="mt-5 h-10 w-full overflow-visible"><polyline points={points} fill="none" stroke="currentColor" strokeWidth="3" vectorEffect="non-scaling-stroke" strokeLinecap="round" strokeLinejoin="round" /></svg>;
}

function MetricCard({ title, value, detail, icon, href, tone = "indigo", children }) {
    const tones = { indigo: "bg-indigo-50 text-indigo-600", emerald: "bg-emerald-50 text-emerald-600", sky: "bg-sky-50 text-sky-600" };
    return <Link href={href} className="group rounded-2xl border border-slate-200/80 bg-white p-5 shadow-[0_2px_12px_rgba(15,23,42,0.035)] transition duration-200 hover:-translate-y-0.5 hover:border-indigo-200 hover:shadow-[0_12px_30px_rgba(79,70,229,0.10)]"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-slate-500">{title}</p><p className="mt-2 text-2xl font-bold tracking-tight text-slate-950">{value}</p></div><span className={`flex h-10 w-10 items-center justify-center rounded-xl text-lg ${tones[tone]}`}>{icon}</span></div><div className="mt-2 text-xs font-semibold text-slate-500">{detail}</div>{children}</Link>;
}

export default function DashboardBento({ user, stats, quoteStats, analytics, scheduledToday, dashboardActivities, formatDate, formatWorkTime }) {
    const [search, setSearch] = useState("");
    const isTechnician = user?.role === "technician";
    const firstName = user?.name?.trim().split(/\s+/)[0] || "";
    const monthlySales = analytics?.monthly_sales || [];
    const sales = monthlySales.map((item) => item.sales);
    const stageTotal = (analytics?.lead_stages || []).reduce((sum, item) => sum + Number(item.value || 0), 0);
    const donutStyle = useMemo(() => {
        if (!stageTotal) return { background: "conic-gradient(#e2e8f0 0 100%)" };
        let start = 0;
        const ranges = analytics.lead_stages.map((item) => { const end = start + (Number(item.value || 0) / stageTotal) * 100; const range = `${item.color} ${start}% ${end}%`; start = end; return range; });
        return { background: `conic-gradient(${ranges.join(",")})` };
    }, [analytics?.lead_stages, stageTotal]);
    const match = (item) => `${item.title || ""} ${item.notes || ""} ${item.client?.name || ""}`.toLocaleLowerCase("ro-RO").includes(search.trim().toLocaleLowerCase("ro-RO"));
    const activities = search ? dashboardActivities.filter(match) : dashboardActivities;
    const appointments = search ? scheduledToday.filter(match) : scheduledToday;
    const conversion = quoteStats.sent ? Math.round((Number(quoteStats.accepted || 0) / Number(quoteStats.sent)) * 100) : 0;

    return <div className="hidden bg-[#f7f8fc] lg:block"><main className="mx-auto max-w-7xl px-6 py-7 xl:px-8">
        <header className="mb-7 flex items-center justify-between gap-6"><div><p className="text-sm font-semibold text-indigo-600">ElectroCRM · spațiu de lucru</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Bună, {firstName}</h1><p className="mt-1 text-sm text-slate-500">Iată activitatea importantă de azi.</p></div><div className="flex w-full max-w-xl items-center gap-3"><label className="relative flex-1"><span className="pointer-events-none absolute left-3 top-2.5 text-slate-400">⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Caută activități sau lucrări..." className="w-full rounded-xl border-slate-200 bg-white py-2.5 pl-9 pr-3 shadow-sm focus:border-indigo-500 focus:ring-indigo-100" /></label><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 bg-white text-lg shadow-sm">🔔</div><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-600 text-sm font-bold text-white shadow-sm">{user?.name?.slice(0, 1)?.toUpperCase()}</div></div></header>

        <div className="grid grid-cols-1 gap-5 xl:grid-cols-3">
            <MetricCard title="Venituri facturate" value={money(analytics?.revenue)} detail={analytics?.revenue_growth === null ? "Nu există comparație anterioară" : `${analytics.revenue_growth >= 0 ? "↑" : "↓"} ${Math.abs(analytics.revenue_growth)}% față de perioada anterioară`} icon="↗" href={route("financial-reports.invoices.index")} tone="emerald"><div className="text-emerald-500"><Sparkline values={sales} /></div></MetricCard>
            <MetricCard title="Oferte câștigate" value={`${quoteStats.accepted || 0} / ${quoteStats.sent || 0}`} detail={`${conversion}% rată de conversie`} icon="◎" href={route("quotes.index")}><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-500" style={{ width: `${conversion}%` }} /></div></MetricCard>
            <MetricCard title="Clienți noi" value={analytics?.new_clients || 0} detail="Adăugați săptămâna aceasta" icon="✦" href={route("clients.index")} tone="sky"><div className="mt-5 flex gap-1">{[1, 2, 3, 4, 5, 6, 7].map((item) => <span key={item} className={`h-6 flex-1 rounded-md ${item <= Math.min(analytics?.new_clients || 0, 7) ? "bg-sky-400" : "bg-slate-100"}`} />)}</div></MetricCard>

            <section className="rounded-2xl border border-slate-200/80 bg-white p-6 shadow-[0_2px_12px_rgba(15,23,42,0.035)] xl:col-span-2"><div className="flex items-start justify-between"><div><h2 className="font-bold text-slate-900">Evoluția vânzărilor</h2><p className="mt-1 text-sm text-slate-500">Facturi emise în ultimele șase luni</p></div><Link href={route("financial-reports.invoices.index")} className="text-sm font-bold text-indigo-600 hover:text-indigo-700">Raport complet →</Link></div><div className="mt-7 h-52 rounded-xl bg-gradient-to-b from-indigo-50/70 to-white p-4"><div className="flex h-full items-end gap-3">{monthlySales.map((item) => { const max = Math.max(...sales, 1); const height = Math.max((Number(item.sales || 0) / max) * 100, 5); return <div key={item.label} className="group flex h-full flex-1 flex-col justify-end"><div className="relative rounded-t-lg bg-gradient-to-t from-indigo-600 to-indigo-400 transition group-hover:from-indigo-700 group-hover:to-sky-400" style={{ height: `${height}%` }}><span className="absolute -top-6 left-1/2 hidden -translate-x-1/2 whitespace-nowrap text-[11px] font-bold text-slate-600 group-hover:block">{money(item.sales)}</span></div><span className="mt-2 text-center text-xs font-semibold text-slate-500">{item.label}</span></div>; })}</div></div></section>

            <section className="rounded-2xl border border-slate-200/80 bg-white p-6 shadow-[0_2px_12px_rgba(15,23,42,0.035)]"><div className="flex items-start justify-between"><div><h2 className="font-bold text-slate-900">Oferte pe stadii</h2><p className="mt-1 text-sm text-slate-500">Situație curentă</p></div><Link href={route("quotes.index")} className="text-sm font-bold text-indigo-600">Vezi →</Link></div><div className="mt-5 flex items-center gap-5"><div className="relative h-28 w-28 shrink-0 rounded-full" style={donutStyle}><div className="absolute inset-4 rounded-full bg-white" /><span className="absolute inset-0 flex items-center justify-center text-lg font-bold text-slate-900">{stageTotal}</span></div><div className="space-y-2">{(analytics?.lead_stages || []).map((stage) => <div key={stage.label} className="flex items-center gap-2 text-xs"><span className="h-2 w-2 rounded-full" style={{ backgroundColor: stage.color }} /><span className="text-slate-500">{stage.label}</span><strong className="ml-auto text-slate-800">{stage.value}</strong></div>)}</div></div></section>

            <section className="rounded-2xl border border-slate-200/80 bg-white p-6 shadow-[0_2px_12px_rgba(15,23,42,0.035)] xl:col-span-2"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-900">Activitate recentă</h2><p className="mt-1 text-sm text-slate-500">Programări și activități din echipă</p></div><Link href={route("calendar.index")} className="text-sm font-bold text-indigo-600">Calendar →</Link></div><div className="mt-4 divide-y divide-slate-100">{appointments.slice(0, 4).map((workOrder) => <Link key={workOrder.id} href={route("work_orders.show", workOrder.id)} className="flex items-center gap-3 py-3 transition hover:translate-x-0.5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-indigo-50">🛠️</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-slate-800">{workOrder.number || "Lucrare"} · {workOrder.client?.name || "Fără client"}</p><p className="mt-0.5 text-xs text-slate-500">{workOrder.type || "Lucrare"} · {workOrder.scheduled_time?.slice(0, 5) || "Fără oră"}</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600">{workStatus[workOrder.status] || workOrder.status}</span></Link>)}{appointments.length === 0 && <p className="py-9 text-center text-sm text-slate-500">Nu există activități care să corespundă căutării.</p>}</div></section>

            <section className="rounded-2xl border border-slate-200/80 bg-white p-6 shadow-[0_2px_12px_rgba(15,23,42,0.035)]"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-900">Task-urile mele</h2><p className="mt-1 text-sm text-slate-500">De rezolvat astăzi</p></div><span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-700">{analytics?.revisions_due || 0} revizii</span></div><div className="mt-4 space-y-2">{activities.slice(0, 4).map((activity) => <button key={activity.id} type="button" disabled={isTechnician} onClick={() => router.patch(route("dashboard.activities.update", activity.id), { status: activity.status === "completed" ? "assigned" : "completed" })} className="flex w-full items-start gap-3 rounded-xl p-2 text-left hover:bg-slate-50 disabled:cursor-default"><span className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-md border ${activity.status === "completed" ? "border-emerald-500 bg-emerald-500 text-white" : "border-slate-300 bg-white"}`}>{activity.status === "completed" ? "✓" : ""}</span><span className={`text-sm font-semibold ${activity.status === "completed" ? "text-slate-400 line-through" : "text-slate-700"}`}>{activity.title}</span></button>)}{activities.length === 0 && <p className="py-7 text-center text-sm text-slate-500">Nu ai task-uri pentru azi.</p>}</div></section>
        </div>
    </main></div>;
}
