<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('chart_accounts', function (Blueprint $table) {
            $table->id(); $table->string('code', 20)->unique(); $table->string('name'); $table->string('class', 50); $table->string('type', 20); $table->boolean('active')->default(true); $table->timestamps();
        });

        $accounts = [
            ['301','Materii prime','Stocuri','activ'],['3021','Materiale auxiliare','Stocuri','activ'],['3022','Combustibili','Stocuri','activ'],['3023','Materiale pentru ambalat','Stocuri','activ'],['3024','Piese de schimb','Stocuri','activ'],['3028','Alte materiale consumabile','Stocuri','activ'],['303','Materiale de natura obiectelor de inventar','Stocuri','activ'],['308','Diferențe de preț la materii prime și materiale','Stocuri','activ'],['331','Produse în curs de execuție','Stocuri','activ'],['341','Semifabricate','Stocuri','activ'],['345','Produse finite','Stocuri','activ'],['346','Produse reziduale','Stocuri','activ'],['347','Mărfuri în curs de aprovizionare','Stocuri','activ'],['351','Materii și materiale aflate la terți','Stocuri','activ'],['354','Produse aflate la terți','Stocuri','activ'],['371','Mărfuri','Stocuri','activ'],['378','Diferențe de preț la mărfuri','Stocuri','activ'],['381','Ambalaje','Stocuri','activ'],
            ['401','Furnizori','Terți','pasiv'],['404','Furnizori de imobilizări','Terți','pasiv'],['408','Furnizori - facturi nesosite','Terți','pasiv'],['409','Furnizori - debitori','Terți','activ'],['4111','Clienți','Terți','activ'],['419','Clienți - creditori','Terți','pasiv'],['421','Personal - salarii datorate','Terți','pasiv'],['423','Personal - ajutoare materiale datorate','Terți','pasiv'],['425','Avansuri acordate personalului','Terți','activ'],['431','Asigurări sociale','Terți','pasiv'],['437','Ajutor de șomaj','Terți','pasiv'],['4423','TVA de plată','TVA','pasiv'],['4424','TVA de recuperat','TVA','activ'],['4426','TVA deductibilă','TVA','activ'],['4427','TVA colectată','TVA','pasiv'],['4428','TVA neexigibilă','TVA','activ'],['4429','TVA de recuperat sau de plată','TVA','activ'],['446','Alte impozite, taxe și vărsăminte asimilate','Terți','pasiv'],['447','Fonduri speciale - taxe și vărsăminte asimilate','Terți','pasiv'],['455','Sume datorate acționarilor/asociaților','Terți','pasiv'],['461','Debitori diverși','Terți','activ'],['471','Cheltuieli înregistrate în avans','Terți','activ'],['473','Decontări din operații în curs de clarificare','Terți','activ'],
            ['5121','Conturi la bănci în lei','Trezorerie','activ'],['5124','Conturi la bănci în valută','Trezorerie','activ'],['5311','Casa în lei','Trezorerie','activ'],['5314','Casa în valută','Trezorerie','activ'],['542','Avansuri de trezorerie','Trezorerie','activ'],['581','Viramente interne','Trezorerie','activ'],
            ['601','Cheltuieli cu materiile prime','Cheltuieli','cheltuială'],['6021','Cheltuieli cu materialele auxiliare','Cheltuieli','cheltuială'],['6022','Cheltuieli privind combustibilii','Cheltuieli','cheltuială'],['6023','Cheltuieli privind materialele pentru ambalat','Cheltuieli','cheltuială'],['6024','Cheltuieli privind piesele de schimb','Cheltuieli','cheltuială'],['6028','Cheltuieli cu alte materiale consumabile','Cheltuieli','cheltuială'],['603','Cheltuieli privind materialele de natura obiectelor de inventar','Cheltuieli','cheltuială'],['604','Cheltuieli privind energia și apa','Cheltuieli','cheltuială'],['605','Cheltuieli privind energia și apa','Cheltuieli','cheltuială'],['607','Cheltuieli privind mărfurile','Cheltuieli','cheltuială'],['611','Cheltuieli cu întreținerea și reparațiile','Cheltuieli','cheltuială'],['612','Cheltuieli cu redevențele, locațiile de gestiune și chiriile','Cheltuieli','cheltuială'],['613','Cheltuieli cu primele de asigurare','Cheltuieli','cheltuială'],['621','Cheltuieli cu colaboratorii','Cheltuieli','cheltuială'],['623','Cheltuieli de protocol, reclamă și publicitate','Cheltuieli','cheltuială'],['624','Cheltuieli cu transportul de bunuri și personal','Cheltuieli','cheltuială'],['626','Cheltuieli poștale și taxe de telecomunicații','Cheltuieli','cheltuială'],['627','Cheltuieli cu serviciile bancare și asimilate','Cheltuieli','cheltuială'],['628','Alte cheltuieli cu serviciile executate de terți','Cheltuieli','cheltuială'],['635','Cheltuieli cu alte impozite, taxe și vărsăminte asimilate','Cheltuieli','cheltuială'],['641','Cheltuieli cu salariile personalului','Cheltuieli','cheltuială'],['645','Cheltuieli privind asigurările și protecția socială','Cheltuieli','cheltuială'],['658','Alte cheltuieli de exploatare','Cheltuieli','cheltuială'],['681','Cheltuieli de exploatare privind amortizările și ajustările','Cheltuieli','cheltuială'],
            ['701','Venituri din vânzarea produselor finite','Venituri','venit'],['704','Venituri din servicii prestate','Venituri','venit'],['705','Venituri din studii și cercetări','Venituri','venit'],['706','Venituri din redevențe, locații de gestiune și chirii','Venituri','venit'],['707','Venituri din vânzarea mărfurilor','Venituri','venit'],['708','Venituri din activități diverse','Venituri','venit'],['711','Venituri aferente costurilor stocurilor de produse','Venituri','venit'],['758','Alte venituri din exploatare','Venituri','venit'],['767','Venituri din sconturi obținute','Venituri','venit'],['771','Venituri din subvenții de exploatare','Venituri','venit'],
        ];
        foreach ($accounts as [$code, $name, $class, $type]) DB::table('chart_accounts')->updateOrInsert(['code' => $code], ['name' => $name, 'class' => $class, 'type' => $type, 'active' => true, 'created_at' => now(), 'updated_at' => now()]);

        $categories = [['Materiale auxiliare','MATAUX','3021','6021','707'],['Combustibili','COMB','3022','6022','707'],['Materiale pentru ambalat','AMB','3023','6023','708'],['Piese de schimb','PSE','3024','6024','707'],['Alte materiale consumabile','CONS','3028','6028','707'],['Produse finite','PF','345','711','701'],['Produse în curs de execuție','PCE','331','711','701'],['Mărfuri în curs de aprovizionare','MCA','347','607','707'],['Ambalaje','AMBJ','381','6023','708'],['Echipamente și unelte','EQ','303','603','707'],['Servicii prestate','SRV','0','628','704']];
        foreach ($categories as [$name, $code, $stock, $expense, $revenue]) DB::table('product_categories')->updateOrInsert(['name' => $name], ['code' => $code, 'inventory_account' => $stock, 'expense_account' => $expense, 'revenue_account' => $revenue, 'active' => true, 'updated_at' => now(), 'created_at' => now()]);
    }
    public function down(): void { Schema::dropIfExists('chart_accounts'); }
};
