<?php
namespace App\Http\Controllers;
use App\Models\{ApplicationSetting, ConsumptionNote, Product, ProductStock, StockMovement, Warehouse, WorkOrder};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Inertia\Inertia;
use Barryvdh\DomPDF\Facade\Pdf;

class ConsumptionNoteController extends Controller
{
    public function index(Request $request) { $this->ensureAccess($request); return Inertia::render('ConsumptionNotes/Index',['notes'=>ConsumptionNote::with(['warehouse','workOrder','items'])->latest('issued_at')->latest('id')->get()]); }
    public function pdf(Request $request, ConsumptionNote $consumptionNote) { $this->ensureAccess($request); $consumptionNote->load(['warehouse','workOrder','items']); return Pdf::loadView('consumption-notes.pdf',['note'=>$consumptionNote])->setPaper('a4')->download('bon-consum-'.$consumptionNote->number.'.pdf'); }
    public function create(Request $request) { $this->ensureAccess($request); return Inertia::render('ConsumptionNotes/Create',['products'=>Product::where('active',true)->orderBy('name')->get(['id','name','code','unit','purchase_price','stock_quantity']),'productStocks'=>ProductStock::get(['product_id','warehouse_id','quantity']),'warehouses'=>Warehouse::where('active',true)->orderBy('name')->get(),'workOrders'=>WorkOrder::latest()->get(['id','number','title'])]); }
    public function store(Request $request) {
        $this->ensureAccess($request);
        $data=$request->validate(['warehouse_id'=>['required','exists:warehouses,id'],'work_order_id'=>['nullable','exists:work_orders,id'],'issued_at'=>['required','date'],'recipient'=>['nullable','string','max:150'],'notes'=>['nullable','string','max:4000'],'items'=>['required','array','min:1'],'items.*.product_id'=>['required','exists:products,id'],'items.*.quantity'=>['required','numeric','gt:0']]);
        DB::transaction(function() use($data,$request){
            $series=data_get(ApplicationSetting::value('document-series',['series'=>['consumption_note'=>'BC']]),'series.consumption_note','BC');
            $number=$series.'-'.now()->format('Y').'-'.str_pad((string)(ConsumptionNote::whereYear('issued_at',now()->year)->lockForUpdate()->count()+1),5,'0',STR_PAD_LEFT);
            $warehouse=Warehouse::findOrFail($data['warehouse_id']); $note=ConsumptionNote::create(collect($data)->except('items')->all()+['number'=>$number,'created_by'=>$request->user()->id]);
            foreach($data['items'] as $item){$product=Product::lockForUpdate()->findOrFail($item['product_id']);$qty=(float)$item['quantity'];$before=(float)$product->stock_quantity;if($before<$qty) abort(422,'Stoc insuficient pentru '.$product->name.'.');if($warehouse->type==='cantitativ_valoric'){$stock=ProductStock::where('product_id',$product->id)->where('warehouse_id',$warehouse->id)->lockForUpdate()->first();if(!$stock){$stock=ProductStock::create(['product_id'=>$product->id,'warehouse_id'=>$warehouse->id,'quantity'=>$before]);}if((float)$stock->quantity<$qty)abort(422,'Stoc insuficient în gestiunea aleasă pentru '.$product->name.'.');$stock->decrement('quantity',$qty);}$after=$before-$qty;$product->update(['stock_quantity'=>$after]);$price=(float)$product->purchase_price;$note->items()->create(['product_id'=>$product->id,'product_name'=>$product->name,'unit'=>$product->unit,'quantity'=>$qty,'unit_price'=>$price,'line_total'=>$qty*$price]);StockMovement::create(['product_id'=>$product->id,'type'=>'out','quantity'=>$qty,'stock_before'=>$before,'stock_after'=>$after,'unit_price'=>$price,'reference_type'=>'consumption_note','reference_id'=>$note->id,'document_number'=>$note->number,'reason'=>'Bon de consum','work_order_id'=>$data['work_order_id']??null,'user_id'=>$request->user()->id,'notes'=>$data['notes']??null]);}
        });
        return redirect()->route('consumption-notes.index')->with('success','Bonul de consum a fost salvat și stocul a fost actualizat.');
    }
    private function ensureAccess(Request $request):void { abort_unless($request->user()?->isAdministrator()||$request->user()?->isSalesManager(),403); }
    public function edit(Request $request, ConsumptionNote $consumptionNote) { $this->ensureAccess($request); return Inertia::render('ConsumptionNotes/Edit',['note'=>$consumptionNote->load('items'),'products'=>Product::where('active',true)->orderBy('name')->get(['id','name','unit','stock_quantity']),'productStocks'=>ProductStock::get(['product_id','warehouse_id','quantity']),'warehouses'=>Warehouse::where('active',true)->orderBy('name')->get(),'workOrders'=>WorkOrder::latest()->get(['id','number','title'])]); }
    public function update(Request $request, ConsumptionNote $consumptionNote) { $this->ensureAccess($request); $data=$request->validate(['warehouse_id'=>['required','exists:warehouses,id'],'work_order_id'=>['nullable','exists:work_orders,id'],'issued_at'=>['required','date'],'recipient'=>['nullable','string','max:150'],'notes'=>['nullable','string','max:4000'],'items'=>['required','array','min:1'],'items.*.product_id'=>['required','exists:products,id'],'items.*.quantity'=>['required','numeric','gt:0']]); DB::transaction(function()use($data,$consumptionNote){$consumptionNote->load('items');foreach($consumptionNote->items as $old){Product::whereKey($old->product_id)->increment('stock_quantity',$old->quantity);ProductStock::where(['product_id'=>$old->product_id,'warehouse_id'=>$consumptionNote->warehouse_id])->increment('quantity',$old->quantity);}$consumptionNote->items()->delete();$warehouse=Warehouse::findOrFail($data['warehouse_id']);foreach($data['items'] as $item){$p=Product::lockForUpdate()->findOrFail($item['product_id']);$q=(float)$item['quantity'];$before=(float)$p->stock_quantity;if($before<$q)abort(422,'Stoc insuficient pentru '.$p->name.'.');$s=ProductStock::firstOrCreate(['product_id'=>$p->id,'warehouse_id'=>$warehouse->id],['quantity'=>$before]);if((float)$s->quantity<$q)abort(422,'Stoc insuficient în gestiunea aleasă pentru '.$p->name.'.');$s->decrement('quantity',$q);$p->update(['stock_quantity'=>$before-$q]);$consumptionNote->items()->create(['product_id'=>$p->id,'product_name'=>$p->name,'unit'=>$p->unit,'quantity'=>$q,'unit_price'=>$p->purchase_price,'line_total'=>$q*(float)$p->purchase_price]);}$consumptionNote->update(collect($data)->except('items')->all());});return redirect()->route('consumption-notes.index')->with('success','Bonul de consum a fost actualizat.');}
}
