import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, router, usePage } from '@inertiajs/react';
import { formatDate } from '@/lib/dateFormat';

export default function Index({ stocks = [], inventories = [] }) {
    const { flash = {} } = usePage().props;
    return <AuthenticatedLayout><Head title="Inventar" /><div className="mx-auto max-w-7xl px-4 py-8">
        {flash.success && <div className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-800">{flash.success}</div>}
        <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-bold">Inventar</h1><p className="mt-1 text-slate-500">Stoc scriptic, inventare emise și diferențe constatate.</p></div><Link href={route('inventory.create')} className="rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white">+ Emite inventar</Link></div>
        <section className="mb-7 overflow-hidden rounded-2xl border bg-white"><div className="border-b p-4"><h2 className="font-bold">Inventare emise</h2></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Număr</th><th className="p-3 text-left">Data</th><th className="p-3 text-left">Gestiune</th><th className="p-3 text-left">Status</th><th className="p-3 text-right">Acțiuni</th></tr></thead><tbody>{inventories.map((inventory) => <tr key={inventory.id} className="border-t"><td className="p-3 font-semibold">{inventory.number}</td><td className="p-3">{formatDate(inventory.inventoried_at)}</td><td className="p-3">{inventory.warehouse?.name}</td><td className="p-3">{inventory.status === 'applied' ? <span className="text-emerald-700">Diferențe aplicate</span> : <span className="text-amber-700">Emis — neaplicat</span>}</td><td className="p-3 text-right"><Link href={route('inventory.show', inventory.id)} className="mr-2 rounded border px-3 py-1.5 text-slate-700">Detalii</Link><a href={route('inventory.pdf', inventory.id)} className="mr-2 rounded border px-3 py-1.5 text-red-700">PDF</a>{inventory.status !== 'applied' && <button onClick={() => confirm('Aplici diferențele constatate în stoc?') && router.post(route('inventory.apply', inventory.id))} className="rounded bg-amber-500 px-3 py-1.5 text-white">Aplică diferențe</button>}</td></tr>)}{!inventories.length && <tr><td colSpan="5" className="p-7 text-center text-slate-500">Nu există inventare emise.</td></tr>}</tbody></table></div></section>
        <section className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-4"><h2 className="font-bold">Situație stoc curentă</h2></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Gestiune</th><th className="p-3 text-left">Produs</th><th className="p-3 text-left">Cod</th><th className="p-3 text-right">Cantitate</th><th className="p-3 text-right">Valoare</th></tr></thead><tbody>{stocks.map((stock) => <tr key={stock.id} className="border-t"><td className="p-3">{stock.warehouse?.name}</td><td className="p-3 font-semibold">{stock.product?.name}</td><td className="p-3">{stock.product?.code || '—'}</td><td className="p-3 text-right">{stock.quantity} {stock.product?.unit}</td><td className="p-3 text-right">{(Number(stock.quantity) * Number(stock.product?.purchase_price || 0)).toFixed(2)} RON</td></tr>)}</tbody></table></div></section>
    </div></AuthenticatedLayout>;
}
