import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout";
import { Head, router, useForm, usePage } from "@inertiajs/react";

const money = (value) => new Intl.NumberFormat("ro-RO", { style: "currency", currency: "RON" }).format(Number(value || 0));
const methodLabel = { bank_transfer: "Ordin de plată", cash: "Numerar", card: "Card", check: "CEC", other: "Altă metodă" };

export default function SupplierPaymentsIndex({ payments = [], suppliers = [], receptions = [] }) {
    const { flash } = usePage().props;
    const form = useForm({ supplier_id: "", reception_id: "", paid_at: new Date().toISOString().slice(0, 10), amount: "", payment_method: "bank_transfer", reference: "", document_number: "", notes: "" });
    const availableReceptions = receptions.filter(reception => !form.data.supplier_id || String(reception.supplier_id) === String(form.data.supplier_id));
    const submit = (event) => { event.preventDefault(); form.post(route("supplier-payments.store"), { onSuccess: () => form.reset("reception_id", "amount", "reference", "document_number", "notes") }); };

    return <AuthenticatedLayout header="Registru de plăți">
        <Head title="Registru de plăți" />
        <div className="mx-auto max-w-7xl space-y-6 px-4 py-8">
            {flash?.success && <div className="rounded-lg bg-emerald-50 p-4 text-emerald-800">{flash.success}</div>}
            <div><h1 className="text-3xl font-bold">Registru de plăți către furnizori</h1><p className="mt-1 text-slate-500">Ordinele de plată sunt evidențiate aici și nu intră în Registrul de casă.</p></div>
            <form onSubmit={submit} className="grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-4"><select required value={form.data.supplier_id} onChange={e => { form.setData("supplier_id", e.target.value); form.setData("reception_id", ""); }} className="rounded border"><option value="">Selectează furnizorul</option>{suppliers.map(supplier => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select><select value={form.data.reception_id} onChange={e => form.setData("reception_id", e.target.value)} className="rounded border"><option value="">Fără recepție asociată</option>{availableReceptions.map(reception => <option key={reception.id} value={reception.id}>{reception.number} · {reception.supplier?.name} · {money(reception.total)}</option>)}</select><input required type="date" value={form.data.paid_at} onChange={e => form.setData("paid_at", e.target.value)} className="rounded border"/><input required min="0.01" step="0.01" type="number" placeholder="Sumă (RON)" value={form.data.amount} onChange={e => form.setData("amount", e.target.value)} className="rounded border"/><select value={form.data.payment_method} onChange={e => form.setData("payment_method", e.target.value)} className="rounded border"><option value="bank_transfer">Ordin de plată</option><option value="cash">Numerar</option><option value="card">Card</option><option value="check">CEC</option><option value="other">Altă metodă</option></select><input placeholder="Nr. OP / referință" value={form.data.reference} onChange={e => form.setData("reference", e.target.value)} className="rounded border"/><input placeholder="Document intern" value={form.data.document_number} onChange={e => form.setData("document_number", e.target.value)} className="rounded border"/><input placeholder="Observații" value={form.data.notes} onChange={e => form.setData("notes", e.target.value)} className="rounded border"/><button disabled={form.processing} className="rounded bg-blue-600 px-4 py-2 font-semibold text-white md:col-span-4">Înregistrează plata</button></form>
            <div className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="p-3">Data</th><th className="p-3">Furnizor</th><th className="p-3">Recepție</th><th className="p-3">Metodă</th><th className="p-3">OP / document</th><th className="p-3 text-right">Sumă</th><th /></tr></thead><tbody>{payments.map(payment => <tr key={payment.id} className="border-t"><td className="p-3">{payment.paid_at}</td><td className="p-3 font-medium">{payment.supplier?.name}</td><td className="p-3">{payment.reception?.number || "—"}</td><td className="p-3">{methodLabel[payment.payment_method] || payment.payment_method}</td><td className="p-3">{payment.reference || payment.document_number || "—"}</td><td className="p-3 text-right font-semibold text-rose-700">{money(payment.amount)}</td><td className="p-3 text-right"><button onClick={() => confirm("Ștergi această plată?") && router.delete(route("supplier-payments.destroy", payment.id))} className="text-rose-600">Șterge</button></td></tr>)}{payments.length === 0 && <tr><td colSpan="7" className="p-8 text-center text-slate-500">Nu există plăți înregistrate.</td></tr>}</tbody></table></div>
        </div>
    </AuthenticatedLayout>;
}
