<!doctype html>
<html lang="ro"><head><meta charset="utf-8"><style>
@page { margin: 18px 22px; } body { font-family: DejaVu Sans, sans-serif; font-size: 9px; color: #172033; } h1 { text-align: center; font-size: 16px; margin: 0 0 5px; } .period { text-align: center; color: #566176; margin-bottom: 14px; } .summary { width: 100%; margin: 0 0 14px; border-collapse: collapse; } .summary td { width: 25%; padding: 8px; border: 1px solid #cbd5e1; } .summary strong { display: block; font-size: 11px; } table { width: 100%; border-collapse: collapse; } th { background: #135B44; color: #fff; padding: 7px; text-align: left; } td { border: 1px solid #cbd5e1; padding: 6px; vertical-align: top; } .number { text-align: right; } .income { color: #087f5b; } .expense { color: #b42318; } .footer { margin-top: 10px; color: #64748b; font-size: 8px; }
</style></head><body>
<h1>REGISTRU DE CASA - INCASARI SI PLATI</h1><div class="period">Perioada: {{ \Carbon\Carbon::parse($filters['date_from'])->format('d.m.Y') }} - {{ \Carbon\Carbon::parse($filters['date_to'])->format('d.m.Y') }}</div>
<table class="summary"><tr><td><strong>Sold initial</strong>{{ number_format($summary['opening_balance'], 2, ',', '.') }} RON</td><td><strong>Incasari numerar</strong>{{ number_format($summary['cash_in'], 2, ',', '.') }} RON</td><td><strong>Plati numerar</strong>{{ number_format($summary['cash_out'], 2, ',', '.') }} RON</td><td><strong>Sold final</strong>{{ number_format($summary['closing_balance'], 2, ',', '.') }} RON</td></tr></table>
<table><thead><tr><th>Data</th><th>Operatiune</th><th>Document / partener</th><th class="number">Incasari</th><th class="number">Plati</th><th class="number">Sold</th></tr></thead><tbody>@php($balance = (float) $summary['opening_balance']) @forelse($transactions as $transaction) @php($balance += (float) $transaction['in'] - (float) $transaction['out'])<tr><td>{{ \Carbon\Carbon::parse($transaction['date'])->format('d.m.Y') }}</td><td>{{ $transaction['type'] }}</td><td>{{ $transaction['document'] }}<br>{{ $transaction['partner'] }}@if($transaction['description'])<br><small>{{ $transaction['description'] }}</small>@endif</td><td class="number income">{{ $transaction['in'] ? number_format($transaction['in'], 2, ',', '.') : '-' }}</td><td class="number expense">{{ $transaction['out'] ? number_format($transaction['out'], 2, ',', '.') : '-' }}</td><td class="number">{{ number_format($balance, 2, ',', '.') }}</td></tr>@empty<tr><td colspan="6" style="text-align:center;padding:14px">Nu exista operatiuni pentru filtrul selectat.</td></tr>@endforelse</tbody></table>
<div class="footer">ElectroCRM - raport generat la {{ now()->format('d.m.Y H:i') }}.</div>
</body></html>
